# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0001_initial'),
        ('stok', '0003_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='depo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='depo.Depo'),
            preserve_default=False,
        ),
    ]
