# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0005_stokpabrik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stok',
            old_name='a_box',
            new_name='atena',
        ),
        migrations.RenameField(
            model_name='stok',
            old_name='a_persen',
            new_name='harmony',
        ),
        migrations.RenameField(
            model_name='stok',
            old_name='h_box',
            new_name='kita',
        ),
        migrations.RenameField(
            model_name='stok',
            old_name='h_persen',
            new_name='picasso',
        ),
        migrations.RemoveField(
            model_name='stok',
            name='k_box',
        ),
        migrations.RemoveField(
            model_name='stok',
            name='k_persen',
        ),
        migrations.RemoveField(
            model_name='stok',
            name='p_box',
        ),
        migrations.RemoveField(
            model_name='stok',
            name='p_persen',
        ),
    ]
