# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0006_auto_20171005_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokpabrik',
            name='stok',
            field=models.FloatField(),
        ),
    ]
