# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKaryawan', models.CharField(max_length=50)),
                ('prof_pic', models.ImageField(blank=True, null=True, upload_to='prof_pic/', verbose_name='Photo Profile')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.Depo')),
            ],
        ),
    ]
