# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeDepo', models.CharField(max_length=15, verbose_name='Kode Depo')),
                ('namaDepo', models.CharField(max_length=25, verbose_name='Nama Depo')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
